export const ACTION_CANCELLED = "ACTION_CANCELLED";

export const SET_CONFIGS = "SET_CONFIGS";
export const SET_CONFIG = "SET_CONFIG";
export const REPLACE_CONFIG_ID = "REPLACE_CONFIG_ID";
export const DELETE_CONFIG = "DELETE_CONFIG";
