version: "3"
services:
 rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "scorpio_rabbitmq"
    ports:
      - "5672:5672"
      - "8083:15672"
    volumes:
      - 'rabbitmq_data:/data'

 mongodb:
    image: "mongo:latest"
    container_name: "scorpio_mongodb"
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: mongodbpassword
      MONGO_INITDB_DATABASE: scorpiodb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodb_data:/data/db
    ports:
       - '27017:27017'

volumes:
  rabbitmq_data:
  mongodb_data: